name: "Daily Version (with TimeZone)"
description: "Creates a new tag using the format YYYY.MM.DD.HHmm, but only if HEAD isn’t already tagged"
icon: calendar
branding:
  icon: "calendar"
  color: "purple"
inputs:
  prefix:
    description: "String to prepend to the tag name"
  force_create:
    description: "Provide `true` and the tag will created no matter the commit had no changed"
outputs:
  created:
    description: "If it exists, a new tag has been created"
  version:
    description: "The latest version tag, either pre-existing or just created"
runs:
  using: "node12"
  main: "distribution/index.js"
